### ISSUE TITLE
method Suspendable.combine(Suspendable... suspendables) is missed

### ISSUE THREAD

**Issue by sinicyn** [TomasMikula/ReactFX#16]
Such useful method was present in the `Guardian` interface :)

**Comment by TomasMikula** [comment]
`Suspendable` could be changed to extend `Guardian`. However, you can easily achieve the same effect like this:

```java
Guardian.combine(
        suspendable1::suspend,
        suspendable2::suspend,
        suspendable3::suspend
)
```

Alternatively, there could be another helper method for the above, instead of `Suspendable` extending `Guardian`:

```java
interface Guardian {
    static Guardian combineSuspendables(Suspendable... suspendables);
}
```

The main reason why `Suspendable` does not extend `Guardian` is that they are basically the same things, so we may want to get rid of one of them.

Also, `Guard` is very much like `Subscription`, the main difference is the context in which they are usually used.

**Comment by TomasMikula** [comment]
That said, if `Guardian` is removed, then yes, `Suspendable.combine(Suspendable...)` would have to be added.

**Comment by TomasMikula** [comment]
`Suspendable.combine(Suspendable...)` is present in the latest snapshot. `Guardian` is deprecated and so is `Indicator`, the only other implementation of `Guardian`.
