### ISSUE TITLE
Create an annotation for boilerplate getter/setter/property methods

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/ReactFX#47]
In GroovyFX, they have the @FXBindable annotation that turns this:
````groovy
@FXBindable
String myString = "hello"
````

into this:
````groovy
private SimpleStringProperty myString = new SimpleStringProperty("hello")
public void setMyString(String value) { myString.setValue(value) }
public String getMyString() { myString.getValue() }
public SimpleStringProperty myStringProperty() { myString }
````

Could something be done for Val and Var? Something like:
````java
@ReactableVal
Double someDouble;

@ReactableVar
Integer someInteger = 4;
```
into
````java
private Val<Double> someDouble;
public double getSomeDouble() { return someDouble.getValue); }
public Val<Double> someDoubleProperty() { return someDouble; }

private Var<Integer> someInteger =Var.newSimpleVar(4);
public int getSomeInteger() { return someInteger.getValue(); }
public void setSomeInteger(int value) { someInteger.setValue(value); }
public Var<Integer> someIntegerProperty() { return someInteger; }
````

or even
````java
@AsFXProperty
private Var<Double> someDouble = Var.newSimpleVar(4.5);
````
that generates the setter/getter/property method

````java
public int getSomeDouble() { return someDouble.getValue(); }
public void setSomeDouble(int value) { someDouble.setValue(value); }
public Var<Integer> someDoubleProperty() { return someDouble; }
````

**Comment by TomasMikula** [comment]
I don't know how it works in Groovy, but I don't think this is possible with Java annotations without bytecode manipulation. I think there would already be some project doing that if it was easy.

**Comment by hastebrot** [comment]
Groovy uses AST transformations for compile-time (and runtime) meta-programming. In order to use auto-completion we also need a DSL descriptor file for the IDE. Eclipse and IDEA formally used two standards for this (DSDL and GDSL), but I think one standard superceeded (not sure about this).

The Spock specification framework uses AST transformations a lot and IDEA/Eclipse already include DSL descriptors for it.

I personally use IDEA live templates to generate the boiler-plate code for JavaFX properties in Java, Groovy and Kotlin and avoid Groovy's AST transformations.

**Comment by TomasMikula** [comment]
Thanks for sharing some details!

**Comment by JordanMartinez** [comment]
Indeed! Thanks for the link and explanation!
